# Generated by Django 5.1.6 on 2025-03-11 05:17

import city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Добавить на главный'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to=city.models.unique_image_path, verbose_name='Картинка'),
        ),
    ]
