# Generated by Django 5.1.6 on 2025-06-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Направления', 'verbose_name_plural': 'Направление'},
        ),
    ]
